stop_programs:
  description: Stop any running programs and zones.

run_zone:
  description: run a specific zone.
  fields:
    entity_id:
      name: Irrigation Program
      description: The irrigation program to run
      required: true
      selector:
        entity:
            integration: irrigationprogram
            domain: switch
    zone:
      name: Zone
      description: Zones to run
      required: true
      selector:
          entity:
            domain: switch
            multiple: true

toggle_zone:
  description: run a specific zone.
  fields:
    entity_id:
      name: Irrigation Program
      description: The irrigation program to run
      required: true
      selector:
        entity:
            integration: irrigationprogram
            domain: switch
    zone:
      name: Zone
      description: Zones to run
      required: true
      selector:
          entity:
            domain: switch
            multiple: true

reset_runtime:
  description: Reset the runtime back to none for the program supports testing.
  fields:
    entity_id:
      name: Entity ID
      description: The irrigation program to run
      required: true
      selector:
        entity:
            integration: irrigationprogram
            domain: switch

run_simulation:
  description: Simulate running a program. The results are shown in the log.
  fields:
    entity_id:
      name: Entity ID
      description: The irrigation program to test
      required: true
      selector:
        entity:
            integration: irrigationprogram
            domain: switch
    scheduled:
      name: Scheduled
      description: Scheduled (true) or manual (false) execution simulation
      default: true
      required: true
      selector:
        boolean:

set_zone_status:
  description: set the zone status.
  fields:
    entity_id:
      name: Entity ID
      description: The zone sensor to set
      required: true
      selector:
        entity:
            integration: irrigationprogram
            domain: sensor
    status:
      name: state
      description: State
      default: 'off'
      required: true
      selector:
        select:
          options:
           - 'on'
           - 'off'
           - 'pending'
           - 'eco'
           - 'disabled'

toggle:
  description: toggle config
  fields:
    entity_id:
      name: Entity ID
      description: Sensor to toggle
      required: true
      selector:
        entity:
            integration: irrigationprogram
            domain: binary_sensor